[pytest]
# Nur unser tests/-Ordner
testpaths = tests

# Nur Dateien, die mit test_ beginnen oder enden auf _test.py
python_files = test_*.py *_test.py

# Verhindert das Rekursions­durchsuchen von site-packages
norecursedirs =
    .venv
    venv
    __pycache__
    .pytest_cache
    */site-packages/*

# Blende Collection-Warnings aus
filterwarnings = ignore:cannot collect 'test_app' because it is not a function.:pytest.PytestCollectionWarning


log_cli = true
log_cli_level = DEBUG
log_cli_format = %(asctime)s [%(levelname)8s] %(name)s: %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S