[pytest]
# Nur unser tests/-Ordner
testpaths = tests

# Nur Dateien, die mit test_ beginnen oder enden auf _test.py
python_files = test_*.py *_test.py

# Verhindert das Rekursions­durchsuchen von site-packages
norecursedirs =
    .venv
    venv
    __pycache__
    .pytest_cache
    */site-packages/*

# Blende Collection-Warnings aus
filterwarnings = ignore:cannot collect 'test_app' because it is not a function.:pytest.PytestCollectionWarning
